apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
  labels:
    name: webapp-volume
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce


