apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
  labels:
    name: webapp-volume
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: ./pv-volume
    type: Directory
