apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mlbsantos/database-webapp:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: ROOT_PASSWORD
                  
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_DATABASE

        volumeMounts:
        - name: webapp-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: webapp-volume
        persistentVolumeClaim:
          claimName: webapp-pvc
